# Generated by Django 2.0.3 on 2021-03-14 16:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quizapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='username',
            field=models.CharField(blank=True, max_length=235, null=True, verbose_name='username'),
        ),
    ]
